service: api-users

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  versionFunctions: false
  deploymentBucket: zadif-sls-deployments
  credentials:
    accessKeyId: ${ env:AWS_ACCESS_KEY_ID }
    secretAccessKey: ${ env:AWS_SECRET_ACCESS_KEY }

plugins:
  # - serverless-offline
  - serverless-domain-manager

package:
  individually: true

functions:
  graphql:
    handler: lambda.graphql
    cors: true
    private: false
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true

custom:
  customDomain:
    domainName: api.zadif.com
    basePath: users
    stage: dev
